### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by elifitch** [mapbox/underreact#112]
Existential crisis time: what is the future of underreact?

When we created the project, the front end build ecosystem was a bit different; create react app was significantly less flexible than it is today for example. Knowledge of how underreact works is highly concentrated (bus factor), and it's uncertain whether investing in institutionalizing underreact knowledge is worth it.

In the meantime, it has been a blocker in a handful of cases, particularly https://github.com/mapbox/underreact/issues/108.

So let's have this discussion. Should we investigate replacing underreact with a community-maintained solution? cc @mapbox/map-design-studio @mapbox/frontend @mapbox/console

**Comment by mbullington** [comment]
Hey! Found this ticket, solution for our consideration: [Vite.js](https://vitejs.dev/)

It's not a one-to-one with `underreact` (it uses ESM & Rollup instead of Webpack), but it seems to be an opinionated build framework, and it *mostly* seems to share our opinions with some nice tooling on top.

Seems like it's used in prod at least at [Repl.it](https://blog.replit.com/vite).

**To be investigated:**

If someone picks up the thread later on Vite, the question is right now it does transpilation via ESBuild which is really fast, but makes our projects' parsing inconsistent across tests (Jest), linting (ESLint), and build (Vite).

Vite supports mostly all Rollup plugins, should we just use Babel and take the speed hit? Or does it not really matter and we can just use ESBuild?
