### ISSUE TITLE
Images not loading using default publicDirectory

### ISSUE THREAD

**Issue by otherwiseman** [mapbox/underreact#77]
I've [added](https://github.com/mapbox/data-warehouse/tree/hey-pages/src/public) some image files to the default `publicDirectory` path (`{project-root}/src/public/`), and am [referencing](https://raw.githubusercontent.com/mapbox/data-warehouse/hey-pages/src/components/GettingStarted.md?token=AIkz6mm3GAdwC42vTJ1NYnbUIFAiDGlvks5cByZzwA%3D%3D) them in the code at `/{site-base-path}/foo.png`. The images are not rendering locally. I've tried various combinations of referencing the image file like `{site-base-path}/foo.png` (without a prepended slash), changing the `siteBasePath` to include a prepended slash, etc, but nothing has worked.

 Any help debugging would be greatly appreciated. Thanks! 

Slack thread for context [here](https://mapbox.slack.com/archives/CACKSFT52/p1543362440084600?thread_ts=1543354067.083700&cid=CACKSFT52)

cc/ @kepta

**Comment by kepta** [comment]
Thanks for opening this issue @otherwiseman , looks like there is a bug in the docs. The default value for `publicDirectory` is `${project-root}/public/` and not `${project-root}/src/public/`.

**Comment by kepta** [comment]
Also, looks like there is some bug in the way development server is hosting static assets. Needs more investigation.

**Comment by otherwiseman** [comment]
Thanks for your assistance and for summarizing here @kepta -- images are working in production now and local development is less of a priority so no worries. Appreciate the timely help!

**Comment by kepta** [comment]
@otherwiseman if you keep you images in the `${project-root}/public/` folder, you should be able to get them wokring by using a relative link, for eg: `<img src="gs01_search.png" >` should work both in development and production modes.

**Comment by davidtheclark** [comment]
Hm, I'd generally recommend (strongly) using root-relative or absolute URLs instead of relative URLs. What do we need to change about Underreact to enable root-relative URLs to work for public assets?

**Comment by benjamintd** [comment]
@davidtheclark I'm running into the same issue with this setup:

- assets are placed in `<project-root>/public/images/image.jpg`
- in my config I have `siteBasePath: '/my-site'`
- during local development, I access my index.html file at `localhost:8080/my-site/index.html` and my file at `localhost:8080/images/image.jpg`
- in production, the index is at `www.example.com/my-site/index.html` and the image at `www.example.com/my-site/images/image.jpg`.

Since I'm loading these images dynamically I can't `import` them all as documented [here](https://github.com/mapbox/underreact#how-do-i-include-svgs-images-and-videos).

How do you think we should reference those assets?

**Comment by davidtheclark** [comment]
Sounds to me like there's a bug in Underreact. In @benjamintd's example, during local development the image *should* be available at `localhost:8080/my-site/images/image.jpg`. @kepta can you please look into this?
